# Generated by Django 4.2 on 2023-05-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('last_name', models.CharField(blank=True, max_length=12, null=True)),
                ('birth', models.DateField(blank=True, max_length=8, null=True)),
                ('mobile_number', models.IntegerField(blank=True, max_length=10, null=True)),
                ('Gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')], default=1)),
            ],
        ),
    ]
