# Generated by Django 4.2 on 2023-05-30 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentsaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsaddress',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_address', to='users.student'),
        ),
    ]
